---
version: draft
author: "Michael Garrett"
date: "`r Sys.Date()`"
title: "Descriptive statistics for attitude toward STEM data"
output: 
  rmarkdown::html_document:
    css: ../css/simple_report.css
vignette: >
  %\VignetteIndexEntry{attitude-analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include = FALSE}
## Load libraries

library(tidyverse)  # map, mutate, filter, gather, select, group_by, summarize
library(broom)
library(knitr)
library(algor)

## RMD options

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  fig.width = 7, 
  fig.height = 5,
  fig.path = "../figures/"
)

## Set local vignette parameters

# NA
```

## Get data

Retrieving data object and creating tidy stacked version

```{r get-dat}

## Read dataset from package data into "Global" environment

# Attitude towards STEM in HS. Make composite scores for math, cs, and stem
load(file.path("..", "data", "attitude_ihs_tbl.rda"))
attitude_ihs_tbl <- attitude_ihs_tbl %>% 
  mutate(math = (calc + trig)/2, csci = comp_prog, 
         stem = rowMeans(select(., calc:eng), na.rm = TRUE))

# Attitude towards STEM work after HS. Make composite scores for cs, and stem
load(file.path("..", "data", "attitude_ahs_tbl.rda"))
attitude_ahs_tbl <- attitude_ahs_tbl %>% 
  mutate(csci = (cs + prog)/2, 
         stem = rowMeans(select(., cs:eng), na.rm = TRUE))

```

## Descriptive statistics

```{r descriptives}

## Mean/SD by pre/post timing for attitudes toward stem work IN HS
# for each course, without composite measures
attitude_ihs_tbl %>% 
  select(-c(ID, phys, math, csci, stem)) %>% 
  group_by(timing) %>% 
  summarize_all(list(M = mean, S = sd), na.rm = TRUE) %>%
  kable(digits = 2, 
        caption = "Mean attitude scores on IN HS measures by class")
# for composite measures
attitude_ihs_tbl %>% 
  select(c(timing, phys, math, csci, stem)) %>% 
  group_by(timing) %>% 
  summarize_all(list(M = mean, S = sd), na.rm = TRUE) %>%
  kable(digits = 2, 
        caption = "Mean attitude on IN HS composite measures")

## Mean/SD by pre/post timing for attitudes toward stem work AFTER HS
# For individual fields, without composite measures
ahs_desc_tbl <- attitude_ahs_tbl %>% 
  select(-c(ID, phys, math, csci, stem)) %>% 
  group_by(timing) %>% 
  summarize_all(list(M = mean, S = sd), na.rm = TRUE) 

ahs_desc_tbl %>%
  kable(digits = 2, 
        caption = "Mean attitude scores on AFTER HS measures by field")

# For composite measures
ahs_composite_desc_tbl <- attitude_ahs_tbl %>% 
  select(c(timing, phys, math, csci, stem)) %>% 
  group_by(timing) %>% 
  summarize_all(list(M = mean, S = sd), na.rm = TRUE) 

ahs_composite_desc_tbl %>%
  kable(digits = 2, 
        caption = "Mean attitude scores on AFTER HS composite measures")
```
## Illustrate change over intervention in key subjects

```{r pre-post-graph}

lbls <- names(ahs_composite_desc_tbl)
lbls <- str_sub(lbls[str_detect(lbls, "_M")], 1, -3)

ahs_composite_desc_tbl %>% 
  select(timing, ends_with("_M")) %>% 
  gather(-timing, key = subject, value = score) %>% 
  ggplot(aes(x = timing, y = score, color = subject, group = subject)) +
    ylim(1, 4) + scale_fill_discrete(name = "Dose", labels = lbls) +
    geom_line(size = 1.5) + geom_point(size = 3) +
    scale_x_discrete(expand = expand_scale(add = .4)) +
    labs(title = "Pre/post mean attitude toward taking a subject in highschool",
         caption = "csci corresponds to 'computer programming', math is the average of 'calculus and trig',\n stem is the average of calculus, trig, physics, advanced chemistry, and computer programming")


```

